stages:
  - execute-sql

execute-select-first-row:
  stage: execute-sql
  image: mysql:latest
  script:
    - export MYSQL_HOST=mysql-rfam-public.ebi.ac.uk
    - export MYSQL_PORT=4497
    - export MYSQL_USER=rfamro
    - export MYSQL_DATABASE=Rfam
    - mysql --user=$MYSQL_USER \
            --host=$MYSQL_HOST \
            --port=$MYSQL_PORT \
            --database=$MYSQL_DATABASE < scripts/select_first_row.sql
  only:
    changes:
      - scripts/select_first_row.sql

execute-select-rat-rna:
  stage: execute-sql
  image: mysql:latest
  script:
    - export MYSQL_HOST=mysql-rfam-public.ebi.ac.uk
    - export MYSQL_PORT=4497
    - export MYSQL_USER=rfamro
    - export MYSQL_DATABASE=Rfam
    - mysql --user=$MYSQL_USER \
            --host=$MYSQL_HOST \
            --port=$MYSQL_PORT \
            --database=$MYSQL_DATABASE < scripts/select_rat_rna.sql
  only:
    changes:
      - scripts/select_rat_rna.sql
